business_profiles = {
    'delivery': {
        'working_hours': 'Segunda a Domingo, das 18h às 23h',
        'products': [
            {'name': 'Pizza Calabresa', 'price': 'R$35,00', 'available': True},
            {'name': 'Pizza Marguerita', 'price': 'R$32,00', 'available': True},
            {'name': 'Pizza Portuguesa', 'price': 'R$36,00', 'available': True},
            {'name': 'Pizza Quatro Queijos', 'price': 'R$38,00', 'available': True},
            {'name': 'Pizza Frango com Catupiry',
                'price': 'R$37,00', 'available': True},
            {'name': 'Pizza Pepperoni', 'price': 'R$39,00', 'available': True},
            {'name': 'Pizza Bacon', 'price': 'R$40,00', 'available': True},
            {'name': 'Pizza Vegetariana', 'price': 'R$34,00', 'available': True},
            {'name': 'Pizza Mexicana', 'price': 'R$41,00', 'available': True},
            {'name': 'Pizza de Chocolate', 'price': 'R$30,00', 'available': True},
            {'name': 'Refrigerante Coca-Cola 2L',
                'price': 'R$10,00', 'available': False},
            {'name': 'Refrigerante Guaraná 2L',
                'price': 'R$9,00', 'available': True},
            {'name': 'Suco de Laranja', 'price': 'R$7,00', 'available': True},
            {'name': 'Água sem Gás', 'price': 'R$4,00', 'available': True},
            {'name': 'Água com Gás', 'price': 'R$4,50', 'available': True},
            {'name': 'Batata Frita', 'price': 'R$12,00', 'available': True},
            {'name': 'Anéis de Cebola', 'price': 'R$10,00', 'available': True},
            {'name': 'Mousse de Maracujá', 'price': 'R$8,00', 'available': True},
            {'name': 'Pudim', 'price': 'R$8,00', 'available': True},
            {'name': 'Brownie', 'price': 'R$9,00', 'available': True},
        ],
        'policies': {
            'delivery_time': '30 a 45 minutos',
            'delivery_fee': 'R$5,00',
            'minimum_order': 'R$25,00',
            'payment_methods': ['Pix', 'Dinheiro', 'Cartão']
        }
    },

    'mechanic': {
        'working_hours': 'Segunda a Sexta, das 8h às 18h; Sábado das 8h às 12h',
        'services': [
            {'name': 'Troca de Óleo', 'price': 'R$45,00',
                'duration': '30 min', 'available': True},
            {'name': 'Alinhamento e Balanceamento', 'price': 'R$80,00',
                'duration': '1h', 'available': True},
            {'name': 'Revisão de Freios', 'price': 'R$120,00',
                'duration': '1h30', 'available': True},
            {'name': 'Revisão de Suspensão', 'price': 'R$150,00',
                'duration': '2h', 'available': True},
            {'name': 'Troca de Bateria', 'price': 'R$25,00', 'duration': '20 min',
                'available': True, 'note': '+ valor da bateria'},
            {'name': 'Troca de Filtros', 'price': 'R$35,00', 'duration': '30 min',
                'available': True, 'note': '+ valor do filtro'},
            {'name': 'Revisão de Injeção Eletrônica', 'price': 'R$180,00',
                'duration': '2h30', 'available': True},
            {'name': 'Revisão de Ar Condicionado', 'price': 'R$95,00',
                'duration': '1h', 'available': True},
            {'name': 'Troca de Velas', 'price': 'R$40,00', 'duration': '30 min',
                'available': True, 'note': '+ valor das velas'},
            {'name': 'Troca de Correia Dentada', 'price': 'R$200,00',
                'duration': '3h', 'available': True, 'note': '+ valor da correia'},
            {'name': 'Troca de Amortecedores', 'price': 'R$80,00', 'duration': '1h30',
                'available': True, 'note': '+ valor dos amortecedores'},
            {'name': 'Revisão de Direção Hidráulica', 'price': 'R$110,00',
                'duration': '1h30', 'available': True},
            {'name': 'Check-up Completo', 'price': 'R$85,00',
                'duration': '1h', 'available': True},
            {'name': 'Troca de Palhetas de Para-brisa', 'price': 'R$20,00',
                'duration': '15 min', 'available': True, 'note': '+ valor das palhetas'},
            {'name': 'Revisão de Sistema de Escape', 'price': 'R$75,00',
                'duration': '45 min', 'available': True},
            {'name': 'Higienização Interna', 'price': 'R$60,00',
                'duration': '1h30', 'available': True},
            {'name': 'Polimento de Faróis', 'price': 'R$50,00',
                'duration': '45 min', 'available': True},
            {'name': 'Revisão Elétrica', 'price': 'R$130,00',
                'duration': '2h', 'available': True},
            {'name': 'Revisão de Embreagem', 'price': 'R$250,00',
                'duration': '4h', 'available': True},
            {'name': 'Serviço de Guincho', 'price': 'R$3,50/km',
                'duration': 'Variável', 'available': True, 'note': 'Valor mínimo R$50,00'}
        ],
        'policies': {
            'appointment_required': True,
            'warranty': '3 meses ou 3.000 km',
            'payment_methods': ['Pix', 'Cartão', 'Dinheiro'],
            'diagnostic_fee': 'R$50,00 (descontado do serviço se aprovado)',
            'emergency_fee': 'Acréscimo de 30% em finais de semana'
        }
    },

    'pharmacy': {
        'working_hours': 'Segunda a Sábado, das 7h às 22h; Domingo das 8h às 20h',
        'products': [
            {'name': 'Dipirona 500mg', 'price': 'R$8,50', 'type': 'Analgésico/Antipirético',
                'available': True, 'requires_prescription': False},
            {'name': 'Paracetamol 750mg', 'price': 'R$12,00', 'type': 'Analgésico/Antipirético',
                'available': True, 'requires_prescription': False},
            {'name': 'Ibuprofeno 400mg', 'price': 'R$15,80', 'type': 'Anti-inflamatório',
                'available': True, 'requires_prescription': False},
            {'name': 'Amoxicilina 500mg', 'price': 'R$18,90', 'type': 'Antibiótico',
                'available': True, 'requires_prescription': True},
            {'name': 'Vitamina C 1g', 'price': 'R$25,50', 'type': 'Suplemento',
                'available': True, 'requires_prescription': False},
            {'name': 'Omeprazol 20mg', 'price': 'R$22,30', 'type': 'Antiácido',
                'available': True, 'requires_prescription': False},
            {'name': 'Losartana 50mg', 'price': 'R$14,70', 'type': 'Anti-hipertensivo',
                'available': True, 'requires_prescription': True},
            {'name': 'Cetirizina 10mg', 'price': 'R$11,40', 'type': 'Antialérgico',
                'available': True, 'requires_prescription': False},
            {'name': 'Loratadina 10mg', 'price': 'R$13,20', 'type': 'Antialérgico',
                'available': True, 'requires_prescription': False},
            {'name': 'Teste de Covid', 'price': 'R$35,00', 'type': 'Exame rápido',
                'available': True, 'requires_prescription': False},
            {'name': 'Termômetro Digital', 'price': 'R$28,90', 'type': 'Equipamento',
                'available': True, 'requires_prescription': False},
            {'name': 'Máscara Cirúrgica (cx 50un)', 'price': 'R$18,50', 'type': 'Proteção',
             'available': True, 'requires_prescription': False},
            {'name': 'Álcool em Gel 70% (500ml)', 'price': 'R$12,80', 'type': 'Higiene',
             'available': True, 'requires_prescription': False},
            {'name': 'Creme para Assaduras', 'price': 'R$16,70', 'type': 'Dermatológico',
                'available': True, 'requires_prescription': False},
            {'name': 'Protetor Solar FPS 50', 'price': 'R$45,60',
                'type': 'Dermatológico', 'available': True, 'requires_prescription': False},
            {'name': 'Multivitamínico Centrum', 'price': 'R$89,90',
                'type': 'Suplemento', 'available': True, 'requires_prescription': False},
            {'name': 'Pomada Nebacetin', 'price': 'R$19,80', 'type': 'Antibiótico tópico',
                'available': True, 'requires_prescription': False},
            {'name': 'Soro Fisiológico 500ml', 'price': 'R$7,20',
                'type': 'Higiene nasal', 'available': True, 'requires_prescription': False},
            {'name': 'Glicose de Dextrose', 'price': 'R$3,50', 'type': 'Suplemento energético',
                'available': True, 'requires_prescription': False},
            {'name': 'Antisséptico Bucal', 'price': 'R$14,90', 'type': 'Higiene oral',
                'available': True, 'requires_prescription': False}
        ],
        'policies': {
            'home_delivery': True,
            'delivery_fee': 'R$8,00',
            'minimum_order': 'R$30,00',
            'payment_methods': ['Pix', 'Dinheiro', 'Cartão', 'Convênio'],
            'requires_prescription_info': True,
            'generic_discount': '15% de desconto em medicamentos genéricos'
        }
    }
}
